### PR TITLE
add applications section

### PR DESCRIPTION
**Pull request by thefenriswolf**
Somebody requested a section for smaller projects and applications. Here is what I think makes sense. You are of course free to tweak this to your liking or reject it entirely.

### CODE REVIEW

**Comment by adds68** [comment]
Hey, this looks really cool, would the idea be that under the applications header you would have multiple of these tables for different types of software like "games" "text editors" etc?

**Comment by thefenriswolf** [comment]
yes that was my idea, I included a template in applications.md which can be copy&pasted for new categories

**Comment by LinuxForEveryone** [comment]
Terrific addition! 
@bashfulrobot thoughts?

@thefenriswolf In the template, what would the Code column be used for?

**Comment by thefenriswolf** [comment]
I provided 2 examples containing information about the programming languages used in that project and a link to the source repo

**Comment by LinuxForEveryone** [comment]
> I provided 2 examples containing information about the programming languages used in that project and a link to the source repo

I see now, thanks for being patient with me :D

**Comment by thefenriswolf** [comment]
@bashfulrobot of course it's not possible to include every program ever. The examples I included were chosen because I know they can use some help. Maybe this can be part of a future inclusion policy?
FOSS Projects with a specific need like [tilix](https://github.com/gnunn1/tilix/issues/1700)

**Comment by LinuxForEveryone** [comment]
@bashfulrobot my only concern is what level of editorial oversight is needed here, so that this Wiki doesn't become bloated and difficult to navigate?

Do we include everything under the sun? If not, what's the inclusion policy?

**Pull request merged**
