### PR TITLE
add contributor guideline

### PR DESCRIPTION
**Pull request by thefenriswolf**
@KillYourFM you suggested having a guideline would be helpful 
here is a quick mockup of what it could look like

### CODE REVIEW

**Comment by Talinx** [comment]
Wouldn't it make sense to change the file name to CONTRIBUTING.md?
https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by thefenriswolf** [comment]
I don't see the difference

**Review by TeamLinux01 — CHANGES_REQUESTED** [review]
Please change contributor-guidelines.md to CONTRIBUTING.md along with the link to the markdown file in README.md.

**Comment by LinuxForEveryone** [comment]
> I don't see the difference

Apparently this actually makes the file visible when people open a new pull request and alerts them to read the contributing guidelines.

**Comment by LinuxForEveryone** [comment]
> @KillYourFM you suggested having a guideline would be helpful
> here is a quick mockup of what it could look like

Awesome effort, thank you very much @thefenriswolf!

**Pull request merged**
