### PR TITLE
Expand Fedora links

### PR DESCRIPTION
**Pull request by mattdm**
We're a big project so we have several different entry points :)

### CODE REVIEW

**Comment by TeamLinux01** [comment]
Would it be better to break out the Operating System out kind of like Applications?
If there are more links for a project, have the main link point to a MarkDown file with the extra links, but if there is only one link just have it point to the main page for that projects contribution.

I personally would like to keep things as clean as possible in the main README.md file.

What do you all think?

**Comment by mattdm** [comment]
I like that. A separate file would allow a short blurb about the project's contributor approach and policies, too, without that being a big distraction.

**Comment by LinuxForEveryone** [comment]
> Would it be better to break out the Operating System out kind of like Applications?
> If there are more links for a project, have the main link point to a MarkDown file with the extra links, but if there is only one link just have it point to the main page for that projects contribution.
> 
> I personally would like to keep things as clean as possible in the main README.md file.
> 
> What do you all think?

+1 here. This may also encourage more information to be provided overall for each project. I'm into it. 

Should I go ahead and merge this and build from there? I'm the noob here and I'll defer to your advice.

**Comment by TeamLinux01** [comment]
The question is do we build a single MarkDown file and a table exactly like Applications.md or create a folder "Operating Systems" and have files like Fedora.md, so each project gets their own page, so to speak.
We could then also make a Template.md in that folder for consistency compared to having the table template at the top of the MarkDown file.

I personally like the folder and individual files for each approach more.

It would probably be better to have the original PR be changed to support the decision we make before we pull it in, after we all agree the way we want to go.

**Comment by LinuxForEveryone** [comment]
@bashfulrobot What are your thoughts?

My only concern is that a separate page for each project _may_ not be justified just based on lack of content for many of them.

**Pull request merged**
